const verbs = [
    { base: "do", past: "did", participle: "done", translation: "делать", example: "She did her homework. The work has been done perfectly." },
    { base: "make", past: "made", participle: "made", translation: "делать", example: "They made lunch for us. The decision has been made by the team." },
    { base: "go", past: "went", participle: "gone", translation: "идти", example: "We went to the museum. The children have gone to the park." },
    { base: "be", past: "was/were", participle: "been", translation: "быть", example: "She was very happy. The museum has been visited by many people." },
    { base: "have", past: "had", participle: "had", translation: "иметь", example: "He had a great time at the party. The hotel has had many guests this week." },
    { base: "take", past: "took", participle: "taken", translation: "брать", example: "She took a bus to work. The picture has been taken already." },
    { base: "see", past: "saw", participle: "seen", translation: "видеть", example: "I saw an interesting movie. The painting has been seen by everyone." },
    { base: "write", past: "wrote", participle: "written", translation: "писать", example: "He wrote an email yesterday. The letter has been written carefully." },
    { base: "buy", past: "bought", participle: "bought", translation: "купить", example: "She bought new shoes. The tickets have been bought online." },
    { base: "eat", past: "ate", participle: "eaten", translation: "есть", example: "We ate breakfast at 8 AM. Lunch has already been eaten." },
    { base: "drink", past: "drank", participle: "drunk", translation: "пить", example: "They drank water during the hike. The juice has been drunk quickly." },
    { base: "fly", past: "flew", participle: "flown", translation: "летать", example: "We flew to Germany last week. The plane has been flown by a new pilot." },
    { base: "leave", past: "left", participle: "left", translation: "оставлять", example: "He left his bag at the station. The keys have been left on the table." },
    { base: "bring", past: "brought", participle: "brought", translation: "приносить", example: "She brought a cake for the party. A new book has been brought for you." },
    { base: "know", past: "knew", participle: "known", translation: "знать", example: "I knew the answer. The song has been known for years." },
    { base: "meet", past: "met", participle: "met", translation: "встречать", example: "They met their teacher yesterday. A lot of friends have been met this year." },
    { base: "find", past: "found", participle: "found", translation: "найти", example: "She found her keys under the sofa. The lost dog has been found." },
    { base: "forget", past: "forgot", participle: "forgotten", translation: "забывать", example: "He forgot his umbrella at the cafe. The password has been forgotten." },
    { base: "give", past: "gave", participle: "given", translation: "давать", example: "She gave me a gift. Help has been given to those in need." },
    { base: "get", past: "got", participle: "got", translation: "получать", example: "I got a present for my birthday. The tickets have been got already." },
    { base: "read", past: "read", participle: "read", translation: "читать", example: "She read an interesting book. The message has been read by everyone." },
    { base: "sleep", past: "slept", participle: "slept", translation: "спать", example: "They slept in a tent last night. The baby has slept for two hours." },
    { base: "spend", past: "spent", participle: "spent", translation: "проводить/тратить", example: "He spent his weekend at the beach. A lot of time has been spent studying." },
    { base: "say", past: "said", participle: "said", translation: "сказать", example: "She said goodbye to her friends. The story has been said many times." },
    { base: "understand", past: "understood", participle: "understood", translation: "понимать", example: "I understood the instructions. The lesson has been understood by everyone." },
    { base: "speak", past: "spoke", participle: "spoken", translation: "говорить", example: "She spoke to her friend yesterday. English has been spoken during the meeting." },
    { base: "choose", past: "chose", participle: "chosen", translation: "выбирать", example: "He chose a blue jacket. A new team leader has been chosen." },
    { base: "tell", past: "told", participle: "told", translation: "рассказывать", example: "She told me the truth. The story has been told many times." },
    { base: "build", past: "built", participle: "built", translation: "строить", example: "They built a new house. The bridge has been built recently." },
    { base: "sing", past: "sang", participle: "sung", translation: "петь", example: "She sang beautifully at the concert. That song has been sung many times." },
    { base: "win", past: "won", participle: "won", translation: "побеждать", example: "He won the game. The competition has been won by our team." }
];
